---
# tasks file for erlang (Debian specific)

- name: Install Erlang Solutions PGP key
  become: yes
  apt_key:
    url: http://packages.erlang-solutions.com/debian/erlang_solutions.asc
    state: present
  tags:
    - erlang

- name: Add Erlang Solutions repository
  become: yes
  apt_repository:
    repo: 'deb http://packages.erlang-solutions.com/debian {{ ansible_distribution_release|lower }} contrib'
    state: present
  tags:
    - erlang

- name: Unhold erlang packages
  command: "apt-mark unhold esl-erlang"
  become: true
  become_user: root
  tags:
    - erlang


- name: Install Erlang packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    force: yes
  with_items:
    - "{{ erlang_packages }}"
  tags:
    - erlang

- name: Hold Erlang packages
  become: yes
  command: "apt-mark hold {{ item }}"
  with_items:
    - "{{ erlang_packages }}"
  tags:
    - erlang
